### ISSUE TITLE
problem in majorNetwork example 

### ISSUE THREAD

**Issue by franc444** [CoRE-RG/SignalsAndGateways#2]
Hi, 

I think there might be a bug in the majorNetwork example (under "examples" directory) as the nodes were not communicating when I ran the simulation, hence the results, e.g., latency, were not computed. 

Thanks,

**Comment by Musteblume** [comment]
Hi,

i looked into it and could not find any error. The communication between nodes is like expected and the result vectors "rxDFLatency" (for data frames) and "rxRFLatency" (for remote frames) is filled with latencies for each can frame.
How much simulation time has passed before you finish the simulation?

Best regrads

**Comment by franc444** [comment]
I run the simulation for the full 1200s as in the omnetpp.ini file and the results still showing me NaN.

**Comment by Musteblume** [comment]
Some questions so that i can try to reproduce this:
* The majorNetwork is our unmodified example?
* On which platform are you working?
* Are you experiencing the same issue with FiCo4OMNeT or CoRE4INET examples?
* Are you experiencing the same issue in the SignalsAndGateways smallNetwork example?

**Comment by franc444** [comment]
> Some questions so that i can try to reproduce this:
> 
> * The majorNetwork is our unmodified example?
Yes it is the same unmodified example. 
> * On which platform are you working?
I am using MacOS BigSur and OMNeT++ version 5.5.1
> * Are you experiencing the same issue with FiCo4OMNeT or CoRE4INET examples?
No, I tried some examples in both projects and they all seem to work fine.
> * Are you experiencing the same issue in the SignalsAndGateways smallNetwork example?
Yes, the same issue exists in the smallNetwork example for all three configurations. 


Thanks

**Comment by Musteblume** [comment]
Hi,

sadly i have no Apple hardware to try it in MacOS.
But i tried in Ubuntu 20.04 and Windows 10. Both are behaving correctly and saving results even after 30s simulation time.
So using our models in a virtual Ubunutu machine could be a solution. We are also not testing on MacOS in our CI.
If you have any further details maybe i can help but i am not able to reproduce this Error.

Best regards

**Comment by franc444** [comment]
Hi, 

Thanks for your effort on this. I guess the solution is to use VM then. 

Kind regards,
